graph "express" {
  express.shape: box
  express.label: "express"
  express -> qs
  qs.shape: box
  qs.label: "qs"
  express -> etag
  etag.shape: box
  etag.label: "etag"
  express -> once
  once.shape: box
  once.label: "once"
  express -> send
  send.shape: box
  send.label: "send"
  express -> vary
  vary.shape: box
  vary.label: "vary"
  express -> debug
  debug.shape: box
  debug.label: "debug"
  express -> fresh
  fresh.shape: box
  fresh.label: "fresh"
  express -> cookie
  cookie.shape: box
  cookie.label: "cookie"
  express -> router
  router.shape: box
  router.label: "router"
  express -> accepts
  accepts.shape: box
  accepts.label: "accepts"
  express -> type-is
  type-is.shape: box
  type-is.label: "type-is"
  express -> parseurl
  parseurl.shape: box
  parseurl.label: "parseurl"
  express -> statuses
  statuses.shape: box
  statuses.label: "statuses"
  express -> encodeurl
  encodeurl.shape: box
  encodeurl.label: "encodeurl"
  express -> mime-types
  mime-types.shape: box
  mime-types.label: "mime-types"
  express -> proxy-addr
  proxy-addr.shape: box
  proxy-addr.label: "proxy-addr"
  express -> body-parser
  body-parser.shape: box
  body-parser.label: "body-parser"
  express -> escape-html
  escape-html.shape: box
  escape-html.label: "escape-html"
  express -> http-errors
  http-errors.shape: box
  http-errors.label: "http-errors"
  express -> on-finished
  on-finished.shape: box
  on-finished.label: "on-finished"
  express -> content-type
  content-type.shape: box
  content-type.label: "content-type"
  express -> finalhandler
  finalhandler.shape: box
  finalhandler.label: "finalhandler"
  express -> range-parser
  range-parser.shape: box
  range-parser.label: "range-parser"
  express -> serve-static
  serve-static.shape: box
  serve-static.label: "serve-static"
  express -> cookie-signature
  cookie-signature.shape: box
  cookie-signature.label: "cookie-signature"
  express -> merge-descriptors
  merge-descriptors.shape: box
  merge-descriptors.label: "merge-descriptors"
  express -> content-disposition
  content-disposition.shape: box
  content-disposition.label: "content-disposition"
}